### ISSUE TITLE
What exact mathematical DFT formula is being used in DoubleFFT_1D ?

### ISSUE THREAD

**Issue by erik132** [wendykierp/JTransforms#17]
Hello,

I need to compute some data to the classic formula described here: 
https://en.wikipedia.org/wiki/Discrete_Fourier_transform

However when I enter the complex numbers 1 + 0i, 2 - 1i, 0 - 1i, -1 + 2i into the complexForward method, then I get a return result of 3 - 2i, 0 - 0.7320508075688774i, 0.0 + 2.7320508075688776i, -1.0 + 2.0i, which is different from the expected result of 2 + 0i, -2 - 2i, 0 - 2i, 4 + 4i.

What kind of mathematical formula does the DoubleFFT_1D class go by. Is it same for all 3 plans? What do I need to do with the end results to achieve the described results?

Erik Soekov

**Comment by wendykierp** [comment]
I cannot reproduce this issue. Using:

```
    public static void main(String[] args)
    {
        double[] data = {1, 0, 2, -1, 0, -1, -1, 2};

        DoubleFFT_1D fft = new DoubleFFT_1D(data.length/2);
        fft.complexForward(data);
        IOUtils.showComplex_1D(data, "Result");

    }
```

I get:

```
Result
-------------------
2,0000
-2,0000 - 2,0000i
-2,0000i
4,0000 + 4,0000i
```

**Comment by erik132** [comment]
It seems that my inputs were corrupted by another dependency. 

Thank you so much for your time. This cleared up a lot of mess :)
