### ISSUE TITLE
release jTransform sources (and javadoc) on maven central

### ISSUE THREAD

**Issue by hoijui** [wendykierp/JTransforms#5]
that would be nice and convenient to be able to read the javadoc in the IDE, and it should be little work for you (the maintainer):
i would recommend the (currently 3rd) answer, by HDave from here:
http://stackoverflow.com/questions/4725668/how-to-deploy-snapshot-with-sources-and-javadoc

**Comment by Sciss** [comment]
Have you seen this: http://search.maven.org/#search|ga|1|g%3A%22com.github.wendykierp%22

**Comment by hoijui** [comment]
ahhh... i was using the "with-dependencies" classifier, which of course makes no sense for a maven project. but it is kind of strange that on the website it is shown as a maven dependency entry, as which it does not make sense. it makes sense to get the jar for stand-alone usage, right? then again, as JTransform is a library, that is kind of an unlikely scenario.
i could imagine it makes sense to refine this part of the website a bit, but otherwise this issue could be closed.
